### ISSUE TITLE
Issues running run.py when using anything newer than 1.4.2

### ISSUE THREAD

**Issue by twadepsvita** [lesserkuma/FlashGBX#18]
I can't seem to get anything working when trying to run it in any version above 1.4.2. Here is the message I get.

> FlashGBX v2.6 by Lesserkuma
> https://github.com/lesserkuma/FlashGBX
> 
> DISCLAIMER: This software is provided as-is and the developer is not responsible for any damage that is caused by the use of it. Use at your own risk!
> Traceback (most recent call last):
>   File "/Users/louise/Downloads/FlashGBX-master/FlashGBX/FlashGBX.py", line 173, in main
>     from . import FlashGBX_CLI
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
>     return original_import(name, *args, **kwargs)
>   File "/Users/louise/Downloads/FlashGBX-master/FlashGBX/FlashGBX_CLI.py", line 19, in <module>
>     from . import hw_GBxCartRW, hw_GBxCartRW_ofw
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
>     return original_import(name, *args, **kwargs)
>   File "/Users/louise/Downloads/FlashGBX-master/FlashGBX/hw_GBxCartRW.py", line 10, in <module>
>     from .Mapper import DMG_MBC, AGB_GPIO
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
>     return original_import(name, *args, **kwargs)
>   File "/Users/louise/Downloads/FlashGBX-master/FlashGBX/Mapper.py", line 6, in <module>
>     from dateutil.relativedelta import relativedelta
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
>     return original_import(name, *args, **kwargs)
> ModuleNotFoundError: No module named 'dateutil'

**Comment by twadepsvita** [comment]
It looks to be working now. Thanks for the advice. I was just running 1.4.2 using a downloaded version off the files, just because it was the only way it would run for me.
